[package]
name = "mmio-hook"
version = "1.0.0"
authors = ["syoch <syoch64@gmail.com>"]
edition = "2018"

[dependencies]
iced-x86 = { version = "1.21.0", default-features = false, features = ["decoder", "no_std"] }
ipc-protocol = { path = "../ipc-protocol" }

[lib]
crate-type = ["staticlib", "cdylib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
